### ISSUE TITLE
Snippet folder not automatically created on linux?

### ISSUE THREAD

**Issue by joshuafcole** [rundis/lt-snippets#13]
```
Error: ENOENT, no such file or directory '/home/josh/.config/LightTable/snippets'
    at Object.fs.readdirSync (fs.js:654:18)
    at lt.objs.files.full_path_ls (file:///home/josh/repos/external/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:19091:134)
    at lt.objs.files.filter_walk (file:///home/josh/repos/external/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:19194:113)
    at load_all (/home/josh/.config/LightTable/plugins/lt_snippets/lt_snippets_compiled.js:68:163)
    at all (/home/josh/.config/LightTable/plugins/lt_snippets/lt_snippets_compiled.js:71:103)
    at snip_hints (/home/josh/.config/LightTable/plugins/lt_snippets/lt_snippets_compiled.js:787:204)
    at Function.__BEH__use_local_hints (/home/josh/.config/LightTable/plugins/lt_snippets/lt_snippets_compiled.js:794:75)
    at d (file:///home/josh/repos/external/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:6200:163)
    at a (file:///home/josh/repos/external/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:6238:18)
    at eval (file:///home/josh/repos/external/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:17924:73)
```

Easy enough to fix on my end, but might stymie newer users.

**Comment by rundis** [comment]
Should be fixed in 0.1.0
