### ISSUE TITLE
"$0" is inserted instead of placing cursor there

### ISSUE THREAD

**Issue by Trapets** [rundis/lt-snippets#21]
Hei Magnus!

LT 0.8.0-alpha on Manjaro 15.09 linux machine.
When snippet is inserted, $0 is displayed also (picture).

LT colnsole error log:

Invalid behavior: :lt.plugins.snippets/complete-snippet

TypeError: snippet.contains is not a function
    at lt.plugins.snippets.__BEH__complete_snippet.__BEH__complete_snippet__delegate (/home/trapets/.config/LightTable/plugins/Snippets/snippets_compiled.js:756:36)
    at Function.lt.plugins.snippets.__BEH__complete_snippet.__BEH__complete_snippet.cljs$lang$applyTo (/home/trapets/.config/LightTable/plugins/Snippets/snippets_compiled.js:787:8)
    at c (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:6194:66)
    at a (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:17774:76)
    at a (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:17808:18)
    at a (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:17819:34)
    at b (file:///opt/LightTable/resources/app/core/node_modules/lighttable/bootstrap.js:17823:14)
    at complete_snippet_form (/home/trapets/.config/LightTable/plugins/Snippets/snippets_compiled.js:283:24)
    at HTMLDivElement.eval (/home/trapets/.config/LightTable/plugins/Snippets/snippets_compiled.js:354:63)

![lt-snip_bug](https://cloud.githubusercontent.com/assets/5584236/10787940/d4d0cdc4-7d7c-11e5-81f9-64a83311c279.png)

**Comment by rundis** [comment]
This should be fixed with version 0.1.1

**Comment by Trapets** [comment]
Yeah, it works.
